version: '3'
services:
  app:
    container_name: testing-course-app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
    ports:
      - "8026:80"
    volumes:
      - ./:/var/www/html
