version: '3'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
    ports:
      - "8026:80"
    volumes:
      - ${PWD}:/var/www/html