name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: docker-compose pull

      - name: 🎻 Install dependencies
        run: make deps

      - name: 🐳 Start all the environment
        run: make start

      - name: ✅ Run the tests
        run: make test
